local addonName, addon = ...

if (GetLocale() ~= 'deDE') then return end

local L = addon.L;

L["always show focused items"] = "Zeige Items im Fokus immer an"
L["always show quest items"] = "Zeige Questitems immer an"
L["always show reagents"] = "Zeige Reagenzien immer an"
L["always show recipes"] = "Zeige Rezepte immer an"
L["Currencies"] = "Währungen"
L["display time"] = "Anzeigedauer"
L["don't display at mailboxes"] = "Keine Anzeige an Briefkästen"
L["don't display in arena"] = "Keine Anzeige in der Arena"
L["don't display on island expeditions"] = "Keine Anzeige während Inselexpeditionen"
L["enable fast autoloot"] = "Aktiviere schnelles Autolooten"
L["focused item ids:"] = "Ids fokussierter Items:"
L["font size"] = "Textgröße"
L["hide health bars while fishing"] = "Verstecke Lebensbalken beim Angeln"
L["hide loot and item roll toasts"] = "Verstecke Loot- und Würfel-Popups"
L["icon scale"] = "Iconskalierung"
L["ignore Honor"] = "Ignoriere Ehre"
L["Items"] = "Items"
L["minimum"] = "Minimum"
L["minimum rarity"] = "Mindestseltenheit"
L["Misc"] = "Extra"
L["Money"] = "Gold"
L["Money counter was reset"] = "Geldzähler wurde zurückgesetzt"
L["Money earned this session: "] = "Während dieser Session verdientes Geld: "
L["Money lost this session: "] = "Während dieser Session verlorenes Geld: "
L["Monochrome"] = "Monochrom"
L["move display"] = "Verschiebe Anzeige"
L["None"] = "Keine"
L["only show focused items"] = "Zeige nur Items im Fokus an"
L["outline mode"] = "Textumrandung"
L["Professions"] = "Berufe"
L["Reputation"] = "Ruf"
L["reset position"] = "Position zurücksetzen"
L["show bag count for stackable items"] = "Zeige Anzahl stapelbarer Items in der Tasche"
L["show currencies"] = "Zeige Währungen"
L["show items based on rarity"] = "Zeige Items nach Seltenheit an"
L["show money"] = "Zeige Geld"
L["show names of all items"] = "Zeige Namen von allen Items"
L["show profession levelups"] = "Zeige Berufsaufstiege"
L["show reputation"] = "Zeige Ruf"
L["show skill levelups"] = "Zeige Fertigkeitsaufstiege"
L["show total count for stackable items"] = "Zeige Gesamtanzahl stapelbarer Items"
L["Thick"] = "Breit"
L["Thick Monochrome"] = "Breit Monochrom"
L["Thin"] = "Dünn"
L["Toggle farming radar"] = "Farmradar an/ausschalten"
L["unknown command"] = "Unbekannter Befehl"
L[ [=[You seem to have used an old Version of Farmer
Check out all the new features in the options!]=] ] = "Du scheinst zuvor eine alte Version von Farmer verwendet zu haben. Sieh dir alle neuen Features in den Optionen an!"

